config/routes.rb
ContactApp::Application.routes.draw do

  resources :pages
  root :to => 'pages#index'

  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
    
  end

  def create
    Mailer.contact(params).deliver
    flash[:notice] = "Your request has been sent successfully."
    render :action => :index
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ContactApp</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/pages/index.html.erb
<h1>Contact</h1>
<%= form_tag pages_path, :method => :post, :id => "contact-form" do %>
<% if flash[:notice] %>
<h4 class="notice"> <%= flash[:notice] %> </h4>
<% end %>
  <ul>
    <li>
      <b>Name:</b><span class="error name" style="display:none"> This field is required</span><br />
      <input type="text" name="name" />
    </li>
    <li>
      <b>EMail:</b><span class="error email" style="display:none"> This field is required</span><br />
      <input type="text" name="email"/>
    </li>
    <li>
      <b>Thema:</b><span class="error thema" style="display:none"> This field is required</span><br />
      <input type="text" name="thema"/>
    </li>
    <li>
      <b>Message:</b><span class="error message" style="display:none"> This field is required</span><br />
      <textarea name="message" cols="70"></textarea>
    </li>
    <li>
      <input type="submit" name="submit" value="submit"/>
    </li>
  </ul>
<% end %>